package com.study.ecommerce.notification;

public enum NotificationType {
    ORDER_COMPLETED,
    ORDER_CANCELLED,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    ORDER_PLACED,
    PAYMENT_COMPLETED,
    PAYMENT_CANCELLED,
    DELIVERY_ASSIGNED,
    DELIVERY_STARTED,

    DELIVERED,
    DELIVERY_COMPLETED;
}
